### ISSUE TITLE
Timeout when call WaitOnDeployment, returns err "the operation has timed out"

### ISSUE THREAD

**Issue by zyfdegh** [gambol99/go-marathon#213] opened 2016-10-08 09:29 UTC
When I start or scale an application, and call client.WaitOnDeployment(id, 0), it returns "the operation has timed out" even if the deployment has done.

**Comment by timoreimann** [comment] 2016-10-08 14:02
@zyfdegh Thanks for reporting. The problem is that a zero-length timeout causes the [timeout channel to fire immediately](https://github.com/gambol99/go-marathon/blob/8908223430b37fc4106d8b8cf1f38cf7124020f1/application.go#L648) unless the [initial existing-and-running check succeeds](https://github.com/gambol99/go-marathon/blob/8908223430b37fc4106d8b8cf1f38cf7124020f1/application.go#L638). I suppose there's a high chance you are hitting the point in-between these two events.

I think we have a few options on the table:

1. Acknowledge the current behavior and don't change anything (except for leaving an additional note in the method's godoc). One could argue that a zero-length timeout is very similar to, say, a one-nanosecond timeout, and thus would yield the same result. (In fact, every timeout below the configured polling wait time would yield the same result, a circumstance that we may want to document at least.)
1. Explicitly disallow a zero-length timeout by returning a specific (new) error. The drawback is that users would have to distinguish between timeout and usage errors. It would also be a breaking API change (which isn't a show stopper per se as we haven't reached version 1.x yet, but users might still get bitten by this; especially since the compiler can't help us here).
1. Same as 2. but `panic`. One could argue that timeout being larger than zero is a given, and violating this invariant represents a logic error that should not be handled gracefully. The Go stdlib does something similar in a few places (e.g., `regexp.MustCompile`).
1. Exercise some special behavior if the timeout value is zero. The most likely candidate I can imagine is to never timeout. I'm not entirely certain if this is a good UX though.

Personally, I'm leaning towards options 3 and 1. Thoughts?

/cc @gambol99

**Comment by zyfdegh** [comment] 2016-10-11 06:50
I mean sometimes it returns "the operation has timed out" **immediately** if timeout is set to 0 or interval like 30.

**Comment by timoreimann** [comment] 2016-10-11 12:49
Disregard everything I wrote: I referenced `WaitOnApplication` all the time when you meant `WaitOnDeployment`. My bad!

Could this be related to #217? Does #218 help you?

Will try to repro.

**Comment by timoreimann** [comment] 2016-10-11 13:15
Was able to repro. It seems unrelated to #217.

**Comment by timoreimann** [comment] 2016-10-12 14:15
Turned out my repro case was flawed. I'm having a hard time now reproducing the issue on master (including #218 as a fix for #217).

`WaitOnDeployment` works fine for me, except for the fact that one has to be cautious to not start to wait for a deployment too early: Even though Marathon returns a deployment ID for operations like `ScaleApplicationInstances`, it does not seem to be immediately available via the deployments endpoint that `WaitOnDeployment` polls, causing it to [return too soon if you're too fast](https://github.com/gambol99/go-marathon/blob/1bdd2f857d78ffcd3b24cb9131f5abb6e01885c0/deployment.go#L132-L134). The workaround is to poll the deployments endpoint via `HasDeployment` until the deployment is available. (That functionality should probably move into go-marathon as well. Or, even better, into Marathon.) But apart from that, things work fine for me.

I _do_ see the issue on `WaitOnApplication` though, and [explained earlier](https://github.com/gambol99/go-marathon/issues/213#issuecomment-252426162) why it's happening there.

@zyfdegh, did you really mean `WaitOnDeployment`? If so, could you provide a repro case?

Thanks.

**Comment by timoreimann** [comment] 2017-07-10 15:39
Closing due to lack of OP activity.

**Closed by timoreimann** 2017-07-10 15:39 UTC
