### ISSUE TITLE
createApplication with tested config fails

### ISSUE THREAD

**Issue by jacob-koren** [gambol99/go-marathon#162] opened 2016-06-08 14:24 UTC
I tried this config directly in my marathon instance and it works.
But using the API it returns: 

**error: Marathon API error: Object is not valid (attribute '': )**

{
  "id": "/appname",
  "container": {
    "type": "DOCKER",
    "docker": {
      "forcePullImage": true,
      "image": "dockerimagelocation",
      "network": "BRIDGE",
      "parameters": [],
      "portMappings": [
        {
          "containerPort": 8080,
          "hostPort": 0,
          "servicePort": 10004,
          "protocol": "tcp",
          "name": "app-port",
          "labels": {}
        },
        {
          "containerPort": 8000,
          "hostPort": 0,
          "servicePort": 10005,
          "protocol": "tcp",
          "name": "debug-port",
          "labels": {}
        },
        {
          "containerPort": 6300,
          "hostPort": 0,
          "servicePort": 10006,
          "protocol": "tcp",
          "name": "code-coverage-port",
          "labels": {}
        }
      ],
      "privileged": true
    },
    "volumes": []
  },
  "cpus": 1,
  "env": {
    "JAVA_OPTS": "-Xmx512m",
    "environment": "Production",
  },
  "healthChecks": [
    {
      "portIndex": 0,
      "path": "/health",
      "maxConsecutiveFailures": 3,
      "protocol": "HTTP",
      "gracePeriodSeconds": 300,
      "intervalSeconds": 60,
      "timeoutSeconds": 20
    }
  ],
  "instances": 1,
  "mem": 1000,
  "ports": null,
  "dependencies": null,
  "uris": [],
  "labels": {
    "HAPROXY_10_VHOST": "app.marathon-lb.dcos.dev.zooz.co",
    "HAPROXY_GROUP": "external"
  },
  "fetch": null
}

**Comment by timoreimann** [comment] 2016-06-08 14:31
I think we have two problems here:

1. The error response not being parsed correctly.
1. A supposed disparity between a particular configuration being fed to Marathon directly vs. routing through go-marathon.

I probably already know what the first point is about: Marathon has been changing (aka breaking) its error responses multiple times, and go-marathon has not been updated to the latest change. (Last time I checked, it wasn't released yet and likely now is.)

Regarding the second point: How did you get the configuration specification into go-marathon? Did you parse it into an `Application` instance? Or did you build it up programmatically?

Also, what version of go-marathon are you using?

**Comment by jacob-koren** [comment] 2016-06-08 14:41
1. Create an Application instance
2. I Forked from 224bc9666affd2cf594f5a2e7e781a2598d630b8

**Comment by timoreimann** [comment] 2016-06-08 14:43
Forgot to ask: What Marathon version are we talking about?

**Comment by jacob-koren** [comment] 2016-06-08 15:01
1.1.1

**Comment by timoreimann** [comment] 2016-06-08 15:12
Thanks for reporting and the details. Will try to reproduce it on my end.

**Comment by timoreimann** [comment] 2016-06-08 15:41
Your JSON specification seems invalid. Have a look yourself: http://jsoneditoronline.org/?id=fcf3128c9e693a80bca06820509ea685

Removing the illegal trailing comma, I was able to deploy your specification just fine with the following sample code:

```go
package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"os"

	marathon "github.com/gambol99/go-marathon"
)

const marathonURLEnvVar = "MARATHON_URL"

func do(marathonURL, specFileName string) error {
	spec, err := ioutil.ReadFile(specFileName)
	if err != nil {
		return fmt.Errorf("failed to read file 'spec.json': %s", err)
	}

	config := marathon.NewDefaultConfig()
	config.URL = marathonURL
	client, err := marathon.NewClient(config)
	if err != nil {
		return fmt.Errorf("failed to create a client for Marathon: %s", err)
	}
	fmt.Println("client created")

	var app marathon.Application
	if err := json.Unmarshal(spec, &app); err != nil {
		return fmt.Errorf("failed to parse JSON file: %s", err)
	}

	created, err := client.CreateApplication(&app)
	if err != nil {
		return fmt.Errorf("failed to create applications: %s", err)
	}
	fmt.Printf("created app with definition: %+v\n", created)

	return nil
}

func main() {
	marathonURL := os.Getenv(marathonURLEnvVar)
	if len(marathonURL) == 0 {
		panic("Marathon URL must not be empty")
	}

	if err := do(marathonURL, "spec.json"); err != nil {
		panic(err)
	}
}
```

**Comment by jacob-koren** [comment] 2016-06-08 16:54
But I didn't created the json directly. I was populating an Application object and using the API

**Comment by timoreimann** [comment] 2016-06-08 17:01
@jacob-koren Ah sorry, I misunderstood you here. Could you then please provide a full example of how you used the API to populate an `application` instance and send out the request?

**Comment by jacob-koren** [comment] 2016-06-08 19:29
func main() {

	argCount := len(os.Args[1:])

	client := createClient();

	fmt.Println("Starting upgrade processs...")

	if argCount == 0 {
		fmt.Println("Please provide appId for the upgrade process: ")
		listApplications(client)
		return
	}

	application := getAppConfig(client, os.Args[1])
	greenApp := new(marathon.Application)

	greenApp.Container = application.Container
	greenApp.ID = application.ID + "-green2"
	greenApp.CPUs = application.CPUs
	greenApp.Mem = application.Mem
	greenApp.Env = application.Env
	greenApp.Instances = application.Instances
	greenApp.HealthChecks = application.HealthChecks
	greenApp.Labels = application.Labels
	greenApp.EmptyUris()
	spew.Dump(greenApp)

	createApplication(client, greenApp)
}


func createClient() marathon.Marathon {
	config := marathon.NewDefaultConfig()
	config.URL = BASE_URL
	config.MarathonToken = MARATHON_TOKEN
	client, err := marathon.NewClient(config)
	if err != nil {
	    log.Fatalf("Failed to create a client for marathon, error: %s", err)
	}

	return client
}

func restartApp(client marathon.Marathon, appId string) {
	if _, err := client.RestartApplication(appId, true); err != nil {
	    log.Fatalf("Failed to restart application error: %s", err)
	} else {
	    log.Printf("Restarted the application")
	}
}

func scaleApp(client marathon.Marathon,appId string, instances int, force bool) {
	if _, err := client.ScaleApplicationInstances(appId, instances, force); err != nil {
	    log.Fatalf("Failed to scale application error: %s", err)
	} else {
	    log.Printf("Scaled the application")
	}
}

func listApplications(client marathon.Marathon) {
	if apps, err := client.ListApplications(nil); err != nil {
	    log.Fatalf("Failed to retrieve applications error: %s", err)
	} else {
	    log.Printf("Applications: %v", apps)
	}
}

func getAppConfig(client marathon.Marathon, appId string) *marathon.Application {
	app, err := client.Application(appId)
	if err != nil {
	    log.Fatalf("Failed to retrieve application config error: %s", err)
	}

	return app
}

func createApplication(client marathon.Marathon, application *marathon.Application) *marathon.Application {
	app, err := client.CreateApplication(application)
	if err != nil {
	    log.Fatalf("Failed to create application %s error: %s", application.ID, err)
	}

	return app	
}

**Comment by jacob-koren** [comment] 2016-06-08 19:31
I'm basically getting the config of a running app and trying to clone it with different appID

**Comment by jacob-koren** [comment] 2016-06-08 20:25
The trailing comma is because i deleted security sensitive data from the message. The API does not produce any trailing commas.

**Comment by timoreimann** [comment] 2016-06-08 21:49
Here's the actual JSON response (that go-marathon currently fails to deserialize) from the error message:

```json
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "\/value",
      "errors": [
        "Requested service port 10000 conflicts with a service port in app \/app-green2",
        "Requested service port 10000 conflicts with a service port in app \/app"
      ]
    }
  ]
}
```

The error seems legitimate since Marathon [does not allow multiple apps to share the same service port](https://mesosphere.github.io/marathon/docs/ports.html). Clearing the service port on the cloned app prior to sending out the creation request solves the problem and lets Marathon pick a free service port on its own:

```go
portMappings := greenApp.Container.Docker.PortMappings
(*portMappings)[0].ServicePort = 0
```

Can you verify that you're seeing the same problem (and solution) on your end?

Will also create an issue to fix the error message deserialization failure.

**Comment by jacob-koren** [comment] 2016-06-09 03:40
Yes, that's exactly it. Thank you!

**Comment by timoreimann** [comment] 2016-06-09 05:36
Glad to hear!

Will close the issue then. Make sure you upgrade go-marathon once #164 has been merged so that future incarnations of this error present themselves more nicely. :-)

**Closed by timoreimann** 2016-06-09 05:36 UTC
