### ISSUE TITLE
By design? ApplicationOk returns true for health checks without results

### ISSUE THREAD

**Issue by oolongbrothers** [gambol99/go-marathon#118] opened 2015-12-16 15:21 UTC
Is it by design that `ApplicationOk` returns `true` if an application has a health check defined but the health check result being `nil`?

We're talking about this section of code here:
```go
	// step: iterate the application checks and look for false
	for _, task := range application.Tasks {
		if task.HealthCheckResult != nil {
			for _, check := range task.HealthCheckResult {
				//When a task is flapping in Marathon, this is sometimes nil
				if check == nil {
					return false, nil
				}
				if !check.Alive {
					return false, nil
				}
			}
		}
	}
```

What I am trying to accomplish is to implement a zero-downtime deployment where an older version of an app (e.g. `/my/app/v1`) should continue to run until the new one (e.g. `/my/app/v2`) has been deployed successfully with all health checks passing.
Polling `ApplicationOk` until that returns `true` does not work, because of the behaviour stated above: For the longest time during a deployment of a new application version, all `HealthCheckResults` of its `Tasks` are `nil` - and therefore `ApplicationOk` returns `true` before the new app version is initialised or even up.

My question is: Am I holding it wrong? ;)
I mean is there a different and better way you designed to do this?
Or is the behaviour described above simply a corner case not accounted for just yet?

**Comment by timoreimann** [comment] 2015-12-17 00:48
I don't know exactly why the decision to consider tasks with missing health checks as healthy was made. It took place along [this commit](https://github.com/gambol99/go-marathon/commit/1a00a84472b9dfbb83e84d8644aaa15098eb2cc2), so hopefully @iderdik remembers. 

My guess is that it's related to https://github.com/mesosphere/marathon/issues/1270. If that's the case, then I'd opt for dropping the logic in question as the issue got fixed in 0.8.1 RC2 (read: a long long time ago).

If that's not the case, then my suggestion would be to change the logic such that we expose a ternary state to the caller: health state is good, bad, or unknown.

**Comment by oolongbrothers** [comment] 2015-12-17 11:41
Thank you for the insight, timoreimann. I realise that I was maybe a bit imprecise with my description though.

The code from 1a00a84472b9dfbb83e84d8644aaa15098eb2cc2 that you reference, is this one:
```go
                //When a task is flapping in Marathon, this is sometimes nil
                if check == nil {
                    return false, nil
                }
```
This is not causing the false positives (unknown == ok) I'm talking about. It's rather the condition on line 372 in combination with the final line of the function:
```go
if task.HealthCheckResult != nil { ... }
...
return true, nil
```
This causes the function to return `true` when there are health checks defined but no health check results known (yet). This was the behaviour of `ApplicationOk` form the start, as added in 1efcfa438b4936edf0a6d332a762cc62136eff75.

The code from 1a00a84472b9dfbb83e84d8644aaa15098eb2cc2 you refer to above is just a recheck if `task.HealthCheckResult` has maybe turned `nil` between lines 372 and 375. I have no idea if this extra check is made obsolete by an upstream bugfix, but it does not do any harm either.

However, both solutions you propose make sense to me. I could do pull request with a proposed solution, but first I would want to come to an agreement as to which of the two fixes should be implemented.
Can a user do anything useful with the information that the health check result in not known yet? Maybe?
Also a factor, how concerned are you about API backwards compatibility?

**Comment by timoreimann** [comment] 2016-04-28 23:23
@oolongbrothers, major apologies for going silent on this one. I can only suspect that I forgot about the issue over last year's Christmas holidays.

I noticed the "offending" nil check has been refactored away by now. Is the existing go-marathon behavior still causing troubles for you? In case it does, I'd be happy to follow you through any required changes -- promised this time. :)

Thanks.

**Comment by jacob-koren** [comment] 2016-06-11 15:59
I also encountered this issue few days ago, will check again today.

**Comment by iderdik** [comment] 2016-07-21 14:29
I'm pretty sure I'm running into this again as well. Several applications that never came up properly (and never passed healthchecks) were still deemed "ok" and allowed the deploy to complete. I can't replicate reliably but it seems to be happening often enough to indicate a real issue.

**Comment by iderdik** [comment] 2016-07-21 14:32
@timoreimann Sorry for missing your comment from December! PR #18 actually made a missing healthcheck indicate failure, not success. Perhaps this issue has resurfaced due to removal of that code?

**Comment by timoreimann** [comment] 2016-07-21 14:41
@iderdik could be. Since several people have run into this problem by, I'll try to find some time to dig deeper.

If anyone happens to have a reproducible use case (@jacob-koren maybe?), I'd be happy to hear. :-)

**Comment by timoreimann** [comment] 2016-07-21 16:05
I think I found the root cause. Will report back later with a thorough analysis and some data. :-)

**Comment by timoreimann** [comment] 2016-07-21 20:00
`curl`ing the Marathon API endpoint continuously while deploying a container, I can see that the `healthChecks` and `tasks` properties get populated progressively. Following are their respective values at various distinct steps:

**Step 1:** both properties yet missing
- healthChecks:
```
<nothing>
```
- tasks:
```
<nothing>
```

**Step 2:** values turn null
- healthChecks:
```
null
```
- tasks:
```
null
```

**Step 3:** both values available with the task not started yet and `healthCheckResults` _missing_
- healthChecks:
```
[
  {
    "path": "/health",
    "protocol": "HTTP",
    "portIndex": 0,
    "gracePeriodSeconds": 3,
    "intervalSeconds": 5,
    "timeoutSeconds": 5,
    "maxConsecutiveFailures": 2,
    "ignoreHttp1xx": false
  }
]
```
- tasks:
```
[
  {
    "id": "app.0bc5c4d4-4f5a-11e6-9956-461ac47997d0",
    "host": "192.168.99.100",
    "ipAddresses": [],
    "ports": [
      31198
    ],
    "startedAt": null,
    "stagedAt": "2016-07-21T15:44:44.514Z",
    "version": "2016-07-21T15:44:43.908Z",
    "slaveId": "ec3708b4-ea0d-4437-b402-d571b212e6ad-S0",
    "appId": "/app"
  }
]
```

**Step 4:** task started (`startedAt` != null) but `healthCheckResults` still missing
- healthChecks:
```
[
  {
    "path": "/health",
    "protocol": "HTTP",
    "portIndex": 0,
    "gracePeriodSeconds": 3,
    "intervalSeconds": 5,
    "timeoutSeconds": 5,
    "maxConsecutiveFailures": 2,
    "ignoreHttp1xx": false
  }
]
```
- tasks:
```
[
  {
    "id": "app.0bc5c4d4-4f5a-11e6-9956-461ac47997d0",
    "host": "192.168.99.100",
    "ipAddresses": [],
    "ports": [
      31198
    ],
    "startedAt": "2016-07-21T15:44:45.463Z",
    "stagedAt": "2016-07-21T15:44:44.514Z",
    "version": "2016-07-21T15:44:43.908Z",
    "slaveId": "ec3708b4-ea0d-4437-b402-d571b212e6ad-S0",
    "appId": "/app"
  }
]
```

**Step 5:** `healthCheckResults` finally becomes available
- healthChecks:
```
[
  {
    "path": "/health",
    "protocol": "HTTP",
    "portIndex": 0,
    "gracePeriodSeconds": 3,
    "intervalSeconds": 5,
    "timeoutSeconds": 5,
    "maxConsecutiveFailures": 2,
    "ignoreHttp1xx": false
  }
]
```
- tasks:
```
[
  {
    "id": "app.0bc5c4d4-4f5a-11e6-9956-461ac47997d0",
    "host": "192.168.99.100",
    "ipAddresses": [],
    "ports": [
      31198
    ],
    "startedAt": "2016-07-21T15:44:45.463Z",
    "stagedAt": "2016-07-21T15:44:44.514Z",
    "version": "2016-07-21T15:44:43.908Z",
    "slaveId": "ec3708b4-ea0d-4437-b402-d571b212e6ad-S0",
    "appId": "/app",
    "healthCheckResults": [
      {
        "alive": true,
        "consecutiveFailures": 0,
        "firstSuccess": "2016-07-21T15:44:49.573Z",
        "lastFailure": null,
        "lastSuccess": "2016-07-21T15:44:49.573Z",
        "taskId": "app.0bc5c4d4-4f5a-11e6-9956-461ac47997d0"
      }
    ]
  }
]
```

If we execute `ApplicationOK` during either step 4 or 5, we are already pass the [first three checks](https://github.com/gambol99/go-marathon/blob/52070b94b0d56263fea23dc12cbfc0b22eb28f4a/application.go#L548-L562) and subsequently try to iterate through all task's health check results. The latter being nil, we fall through to the return statement (as pointed out by @oolongbrothers originally).

Given that we already know about the existence of custom health checks at the time we start iterating (because [this check](https://github.com/gambol99/go-marathon/blob/52070b94b0d56263fea23dc12cbfc0b22eb28f4a/application.go#L548-L562) would have returned otherwise), I believe the right thing to do here is to add another check for `task.HealthCheckResults` being nil/empty and return false if that's the case.

I'll do some further testing to confirm my findings. In the meantime, I'd appreciate if someone could take a second verifying look. Thanks!

/cc @gambol99

**Closed** 2016-07-23 07:06 UTC

**Comment by timoreimann** [comment] 2016-07-23 07:08
The issue should hopefully be fixed now. If you experience the problem again with the latest version of go-marathon, please post to this ticket again and / or reopen it.

Thanks!
