### ISSUE TITLE
TestRegisterSEESubscriptionReconnectsStreamOnError fails on windows

### ISSUE THREAD

**Issue by ondrej-smola** [gambol99/go-marathon#296] opened 2017-07-06 10:41 UTC
```
--- FAIL: TestRegisterSEESubscriptionReconnectsStreamOnError (0.50s)
        Error Trace:    subscription_test.go:429
        Error:          did not receive event in time
```

I am able to reproduce it only on Windows (tested golang 1.8.3 and 1.6.2, Windows 10 Pro Creators Update).  Can be solved by setting http client timeout to e.g. 50 milliseconds -  PR ok?

**Comment by timoreimann** [comment] 2017-07-06 11:38
I also ran across this and came to the conclusion that the timeout may be set too low.

@marco-jantke WDYT?

**Comment by marco-jantke** [comment] 2017-07-06 12:00
This sounds as the initial connect happens at a moment in time the endpoint1 of that test case is just closing and the connection attempt stays idle. Otherwise I could not explain myself why a client timeout could fix this. @ondrej-smola out of curiosity can you add a short sleep before this [line](https://github.com/gambol99/go-marathon/blob/dd6cbd4c2d71294a19fb89158f2a00d427f174ab/subscription_test.go#L410) and check whether this also fixes the issue?

Anyway we were longer experiencing flakiness in that test case without having an explanation. Great catch therefore @ondrej-smola, PRs are happily welcome :)

**Comment by ondrej-smola** [comment] 2017-07-06 12:31
@marco-jantke sleep before endpoint1.Close() does not work

**Comment by ondrej-smola** [comment] 2017-07-06 12:47
Also notice that timeout must be very low < 100 ms. Otherwise it fails even when SSEConnectWaitTime or eventPublishTimeout is set to seconds)

Logs during registerSSESubscription (with custom log line)
```
Error subscribing to Marathon event stream: Get http://127.0.0.1:63307/v2/events: dial tcp 127.0.0.1:63307: i/o timeout
Error subscribing to Marathon event stream: Get http://127.0.0.1:63307/v2/events: dial tcp 127.0.0.1:63307: i/o timeout
Error subscribing to Marathon event stream: Get http://127.0.0.1:63307/v2/events: dial tcp 127.0.0.1:63307: i/o timeout
Listen on SSE subscription 2017-07-06 12:43:58.124575 +0000 UTC
Error on SSE subscription: EOF, 2017-07-06 12:44:01.6705144 +0000 UTC
--- FAIL: TestRegisterSEESubscriptionReconnectsStreamOnError (4.00s)
```
Hangs for 3 seconds inside eventsource.SubscribeWith call

**Comment by marco-jantke** [comment] 2017-07-06 13:42
How did you produce this logoutput? Is it now with a client timeout setting? Which timeout setting are you using in specific? I am a bit surprised about it, because it should mark the first cluster member as down immediately, given it can not establish a connection to it. In general a client timeout is tricky here, because it is a SSE connection and so that connection should stay open. So only a timeout on the initial Dial would make sense to me.

If you have a fix reproducible fix for that case btw, feel free to open the PR and we can discuss from there. Then I can also verify it on my machine and Travis will also build it automatically.

**Comment by ondrej-smola** [comment] 2017-07-06 14:04
I think i found few parts that can together cause this problem. 

1. Config uses default go client when no HTTPClient client, this is bad by design IMHO as it does not set any timeout [good [explanation](https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779)
2. in  https://github.com/ondrej-smola/go-marathon/blob/master/testing_utils_test.go#L175 first endpoint URL is registered 3 times, so when first attempt fails, it tries seconds (duplicate) and without timeout it hangs here

I will try to remove all debug lines and create PR ... maybe split it to 2 separate PRs?

**Comment by timoreimann** [comment] 2017-07-06 15:17
@ondrej-smola two separate PRs would be preferable -- thanks!

**Closed** 2017-08-07 21:02 UTC
